services:
  reverse_proxy:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - front-tier
      - back-tier
    volumes:
      - ./sites-enabled:/etc/nginx/conf.d



  backend:
          #   image: node:18
    build: 
      context: .
      dockerfile: ./backend.Dockerfile
      #    volumes:
      #      - db-data:/etc/data
    networks:
      - back-tier

        #volumes:
        #  db-data:
        #    driver: flocker
        #    driver_opts:
        #      size: "10GiB"

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
